require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/statistics", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Statistic. As you add validations to Statistic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Statistic.create! valid_attributes
      get statistics_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      statistic = Statistic.create! valid_attributes
      get statistic_url(statistic)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_statistic_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      statistic = Statistic.create! valid_attributes
      get edit_statistic_url(statistic)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Statistic" do
        expect {
          post statistics_url, params: { statistic: valid_attributes }
        }.to change(Statistic, :count).by(1)
      end

      it "redirects to the created statistic" do
        post statistics_url, params: { statistic: valid_attributes }
        expect(response).to redirect_to(statistic_url(Statistic.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Statistic" do
        expect {
          post statistics_url, params: { statistic: invalid_attributes }
        }.to change(Statistic, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post statistics_url, params: { statistic: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested statistic" do
        statistic = Statistic.create! valid_attributes
        patch statistic_url(statistic), params: { statistic: new_attributes }
        statistic.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the statistic" do
        statistic = Statistic.create! valid_attributes
        patch statistic_url(statistic), params: { statistic: new_attributes }
        statistic.reload
        expect(response).to redirect_to(statistic_url(statistic))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        statistic = Statistic.create! valid_attributes
        patch statistic_url(statistic), params: { statistic: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested statistic" do
      statistic = Statistic.create! valid_attributes
      expect {
        delete statistic_url(statistic)
      }.to change(Statistic, :count).by(-1)
    end

    it "redirects to the statistics list" do
      statistic = Statistic.create! valid_attributes
      delete statistic_url(statistic)
      expect(response).to redirect_to(statistics_url)
    end
  end
end
